//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class academia
    {
        public int id_academia { get; set; }
        public string nombre { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> id_direccion { get; set; }
    
        public virtual direccion direccion { get; set; }
    }
}
