//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public administrador()
        {
            this.administrador_imagen = new HashSet<administrador_imagen>();
        }
    
        public int id_admin { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<short> sexo { get; set; }
        public string dni { get; set; }
        public Nullable<long> telefono { get; set; }
        public string mail { get; set; }
        public Nullable<int> id_direccion { get; set; }
        public Nullable<long> telefono_emergencia { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<short> baja_logica { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public Nullable<int> id_pais { get; set; }
    
        public virtual direccion direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<administrador_imagen> administrador_imagen { get; set; }
        public virtual pais pais { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        public virtual seguridad_usuario seguridad_usuario { get; set; }
    }
}
