//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public int id_alumno { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<int> id_faja { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<short> sexo { get; set; }
        public int dni { get; set; }
        public Nullable<int> telefono { get; set; }
        public string mail { get; set; }
        public Nullable<int> id_direccion { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
    }
}
