//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class clase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clase()
        {
            this.inscripcion_clase = new HashSet<inscripcion_clase>();
            this.horario = new HashSet<horario>();
        }
    
        public int id_clase { get; set; }
        public Nullable<int> id_tipo_clase { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> id_profe { get; set; }
        public Nullable<int> id_direccion { get; set; }
        public string nombre { get; set; }
    
        public virtual direccion direccion { get; set; }
        public virtual tipo_clase tipo_clase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inscripcion_clase> inscripcion_clase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario> horario { get; set; }
    }
}
