//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pago_clase
    {
        public int id_detalle { get; set; }
        public Nullable<int> id_pago_clase { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string mes { get; set; }
        public int id_forma_pago { get; set; }
        public Nullable<short> recargo { get; set; }
        public Nullable<int> id_pago_multiple { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento_cumple { get; set; }
        public Nullable<System.DateTime> fecha_desde_cumple { get; set; }
    
        public virtual forma_pago forma_pago { get; set; }
        public virtual pago_clase pago_clase { get; set; }
        public virtual pago_multiple pago_multiple { get; set; }
    }
}
