//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_reserva
    {
        public int id_estado_reserva { get; set; }
        public Nullable<int> id_reserva { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string comentario { get; set; }
        public Nullable<short> actual { get; set; }
        public Nullable<int> id_estado { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual reserva reserva { get; set; }
    }
}
