//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_especial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evento_especial()
        {
            this.inscripcion_evento = new HashSet<inscripcion_evento>();
            this.pago_evento = new HashSet<pago_evento>();
            this.evento_especial_imagen = new HashSet<evento_especial_imagen>();
        }
    
        public int id_evento { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> id_tipo_evento { get; set; }
        public string hora_cierre { get; set; }
        public string hora { get; set; }
    
        public virtual estado estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inscripcion_evento> inscripcion_evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_evento> pago_evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_especial_imagen> evento_especial_imagen { get; set; }
        public virtual tipo_evento_especial tipo_evento_especial { get; set; }
        public virtual sede sede { get; set; }
    }
}
