//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_especial_imagen
    {
        public int id_evento_imagen { get; set; }
        public int id_evento { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual evento_especial evento_especial { get; set; }
    }
}
