//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public int id_horario { get; set; }
        public string nombre_dia { get; set; }
        public string hora_desde { get; set; }
        public string hora_hasta { get; set; }
        public Nullable<int> id_clase { get; set; }
    
        public virtual clase clase { get; set; }
    }
}
