//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripcion_evento
    {
        public int id_inscripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_participante { get; set; }
        public Nullable<int> id_evento { get; set; }
        public string hora { get; set; }
    
        public virtual evento_especial evento_especial { get; set; }
        public virtual participante_evento participante_evento { get; set; }
    }
}
