//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago_clase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pago_clase()
        {
            this.detalle_pago_clase = new HashSet<detalle_pago_clase>();
        }
    
        public int id_pago_clase { get; set; }
        public Nullable<int> id_alumno { get; set; }
        public Nullable<int> id_clase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pago_clase> detalle_pago_clase { get; set; }
        public virtual alumno alumno { get; set; }
        public virtual clase clase { get; set; }
    }
}
