//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago_multiple
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pago_multiple()
        {
            this.pago_clase = new HashSet<pago_clase>();
            this.pago_evento = new HashSet<pago_evento>();
            this.pago_torneo = new HashSet<pago_torneo>();
        }
    
        public int id_pago { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int id_forma_pago { get; set; }
        public decimal monto_total { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string dni { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string estado_mercado_pago { get; set; }
    
        public virtual forma_pago forma_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_clase> pago_clase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_evento> pago_evento { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        public virtual seguridad_usuario seguridad_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago_torneo> pago_torneo { get; set; }
    }
}
