//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguridad_grupoxopcion
    {
        public int id_grupoxopcion { get; set; }
        public int id_grupo { get; set; }
        public string clave_opcion { get; set; }
        public string ejecutar { get; set; }
        public string modificar { get; set; }
        public string eliminar { get; set; }
        public string ver { get; set; }
        public string agregar { get; set; }
    
        public virtual seguridad_grupo seguridad_grupo { get; set; }
        public virtual seguridad_opcion seguridad_opcion { get; set; }
    }
}
