//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSS_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguridad_usuarioxgrupo
    {
        public int id_usuarioxgrupo { get; set; }
        public int id_usuario { get; set; }
        public int id_grupo { get; set; }
    
        public virtual seguridad_grupo seguridad_grupo { get; set; }
        public virtual seguridad_usuario seguridad_usuario { get; set; }
    }
}
